### ISSUE TITLE
Migreate package management tools  to dep or vgo(modules)

### ISSUE THREAD

**Issue by dmnlk** [kazeburo/chocon#18]
dep
>dep was the "official experiment.
https://golang.github.io/dep/

modules
require golang 1.11 or higher
https://github.com/golang/go/wiki/Modules

**Comment by dmnlk** [comment]
#20 go mod sample

**Comment by kazeburo** [comment]
I want to use dep.

**Comment by kazeburo** [comment]
merged #22. Thank you.
